#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ totality004.idr -o totality004
./totality004
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --check totality004a.idr
rm -f totality004 *.ibc
