#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --nocolour trampoline.idr -o trampoline
java -Xss10m  \
  -cp \
  idris-jvm-runtime.jar:trampoline-classes \
  main.Main
rm -f trampoline trampoline.ibc
