-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java.Util

import public Java.Lang
import public Java.Util.Function
import public System.FFI

public export
data List : Type -> Type where [external]

public export
data Iterator : Type -> Type where [external]

public export
data Collection : Type -> Type where [external]

public export
data ListIterator : Type -> Type where [external]

public export
data Spliterator : Type -> Type where [external]

public export
data SequencedCollection : Type -> Type where [external]

public export %inline
Comparator : Type -> Type
Comparator ty0 = (Struct "java/util/Comparator compare" [], Java.Lang.Object -> Java.Lang.Object -> Int)

public export
Inherits (Java.Util.List e) (Java.Util.SequencedCollection e) where

public export
Inherits (Java.Util.List e) (Java.Util.Collection e) where

public export
Inherits (Java.Util.List e) (Java.Lang.Iterable e) where

public export
Inherits (Java.Util.List e) Java.Lang.Object where

namespace List
  %foreign "jvm:.size(i:java/util/List int),java/util/List"
  prim__size : Java.Util.List e -> PrimIO Int
  export %inline
  size : (HasIO io) => Java.Util.List e -> io Int
  size arg0 = primIO (prim__size arg0)

  %foreign "jvm:of(java/util/List),i:java/util/List"
  prim__of_ : PrimIO (Java.Util.List e)
  export %inline
  of_ : (HasIO io) => io (Java.Util.List e)
  of_ = primIO prim__of_

  namespace Of1
    %foreign "jvm:of(java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> io (Java.Util.List e)
    of_ arg0 = primIO (prim__of_ arg0)

  namespace Of2
    %foreign "jvm:of(java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 = primIO (prim__of_ arg0 arg1)

  namespace Of3
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 = primIO (prim__of_ arg0 arg1 arg2)

  namespace Of4
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 = primIO (prim__of_ arg0 arg1 arg2 arg3)

  namespace Of5
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 arg4 = primIO (prim__of_ arg0 arg1 arg2 arg3 arg4)

  namespace Of6
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 arg4 arg5 = primIO (prim__of_ arg0 arg1 arg2 arg3 arg4 arg5)

  namespace Of7
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 = primIO (prim__of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6)

  namespace Of8
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 arg7 = primIO (prim__of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 arg7)

  namespace Of9
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> e -> e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> e -> e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 arg7 arg8 = primIO (prim__of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 arg7 arg8)

  namespace Of10
    %foreign "jvm:of(java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : e -> e -> e -> e -> e -> e -> e -> e -> e -> e -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => e -> e -> e -> e -> e -> e -> e -> e -> e -> e -> io (Java.Util.List e)
    of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 arg7 arg8 arg9 = primIO (prim__of_ arg0 arg1 arg2 arg3 arg4 arg5 arg6 arg7 arg8 arg9)

  namespace Of1_2
    %foreign "jvm:of([java/lang/Object java/util/List),i:java/util/List"
    prim__of_ : Object -> PrimIO (Java.Util.List e)
    export %inline
    of_ : (HasIO io) => Object -> io (Java.Util.List e)
    of_ arg0 = primIO (prim__of_ arg0)
