#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --nocolour totality003.idr --check
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --nocolour totality003a.idr --check
rm -f *.ibc
