#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ totality005.idr --total --check
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ totality005.idr -o totality005
./totality005
rm -f totality005 *.ibc
