-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java.Io

import Java.Lang

public export
data Serializable : Type where [external]
