-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java.Util

import public Java.Lang
import public Java.Util.Function
import public Java.Io
import public System.FFI

public export
data ArrayList : Type -> Type where [external]

public export
data HashMap : Type -> Type -> Type where [external]

public export
data Collection : Type -> Type where [external]

public export
data ListIterator : Type -> Type where [external]

public export
data Iterator : Type -> Type where [external]

public export
data List : Type -> Type where [external]

public export
data Spliterator : Type -> Type where [external]

public export
data Map : Type -> Type -> Type where [external]

public export
data Set : Type -> Type where [external]

public export
data Map_Entry : Type -> Type -> Type where [external]

public export
data AbstractList : Type -> Type where [external]

public export
data RandomAccess : Type where [external]

public export
data AbstractCollection : Type -> Type where [external]

public export
data SequencedCollection : Type -> Type where [external]

public export
data AbstractMap : Type -> Type -> Type where [external]

public export %inline
Comparator : Type -> Type
Comparator ty0 = (Struct "java/util/Comparator compare" [], Java.Lang.Object -> Java.Lang.Object -> Int)

public export
Inherits (Java.Util.ArrayList e) (Java.Util.AbstractList e) where

public export
Inherits (Java.Util.ArrayList e) (Java.Util.List e) where

public export
Inherits (Java.Util.ArrayList e) Java.Util.RandomAccess where

public export
Inherits (Java.Util.ArrayList e) Java.Lang.Cloneable where

public export
Inherits (Java.Util.ArrayList e) Java.Io.Serializable where

public export
Inherits (Java.Util.ArrayList e) (Java.Util.AbstractCollection e) where

public export
Inherits (Java.Util.ArrayList e) (Java.Util.SequencedCollection e) where

public export
Inherits (Java.Util.ArrayList e) (Java.Util.Collection e) where

public export
Inherits (Java.Util.ArrayList e) (Java.Lang.Iterable e) where

public export
Inherits (Java.Util.ArrayList e) Java.Lang.Object where

public export
Inherits (Java.Util.HashMap k v) (Java.Util.AbstractMap k v) where

public export
Inherits (Java.Util.HashMap k v) (Java.Util.Map k v) where

public export
Inherits (Java.Util.HashMap k v) Java.Lang.Cloneable where

public export
Inherits (Java.Util.HashMap k v) Java.Io.Serializable where

public export
Inherits (Java.Util.HashMap k v) Java.Lang.Object where

namespace ArrayList
  %foreign "jvm:<init>(java/util/ArrayList),java/util/ArrayList"
  prim__new : PrimIO (Java.Util.ArrayList rt_0)
  export %inline
  new : (HasIO io) => io (Java.Util.ArrayList rt_0)
  new = primIO prim__new

  %foreign "jvm:.size(java/util/ArrayList int),java/util/ArrayList"
  prim__size : Java.Util.ArrayList e -> PrimIO Int
  export %inline
  size : (HasIO io) => Java.Util.ArrayList e -> io Int
  size arg0 = primIO (prim__size arg0)

  %foreign "jvm:.get(java/util/ArrayList int java/lang/Object),java/util/ArrayList"
  prim__get : Java.Util.ArrayList e -> Int -> PrimIO e
  export %inline
  get : (HasIO io) => Java.Util.ArrayList e -> Int -> io e
  get arg0 arg1 = primIO (prim__get arg0 arg1)

  %foreign "jvm:.add(java/util/ArrayList java/lang/Object boolean),java/util/ArrayList"
  prim__add : Java.Util.ArrayList e -> e -> PrimIO Bool
  export %inline
  add : (HasIO io) => Java.Util.ArrayList e -> e -> io Bool
  add arg0 arg1 = primIO (prim__add arg0 arg1)

  %foreign "jvm:.sort(java/util/ArrayList java/util/Comparator void),java/util/ArrayList"
  prim__sort : Java.Util.ArrayList e -> Java.Util.Comparator e -> PrimIO ()
  export %inline
  sort : {e : Type} -> (HasIO io) => Java.Util.ArrayList e -> (e -> e -> Int) -> io ()
  sort {e} arg0 arg1 = primIO (prim__sort arg0 (jlambda arg1))

  namespace Add2
    %foreign "jvm:.add(java/util/ArrayList int java/lang/Object void),java/util/ArrayList"
    prim__Add2 : Java.Util.ArrayList e -> Int -> e -> PrimIO ()
    export %inline
    add : (HasIO io) => Java.Util.ArrayList e -> Int -> e -> io ()
    add arg0 arg1 arg2 = primIO (prim__Add2 arg0 arg1 arg2)

namespace HashMap
  %foreign "jvm:<init>(java/util/HashMap),java/util/HashMap"
  prim__new : PrimIO (Java.Util.HashMap rt_0 rt_1)
  export %inline
  new : (HasIO io) => io (Java.Util.HashMap rt_0 rt_1)
  new = primIO prim__new

  %foreign "jvm:.get(java/util/HashMap java/lang/Object java/lang/Object),java/util/HashMap"
  prim__get : Java.Util.HashMap k v -> Java.Lang.Object -> PrimIO v
  export %inline
  get : (HasIO io, Inherits a1 Java.Lang.Object) => Java.Util.HashMap k v -> a1 -> io (Maybe v)
  get arg0 arg1 = nullableToMaybe <$> primIO (prim__get arg0 (the Java.Lang.Object (subtyping arg1)))

  %foreign "jvm:.put(java/util/HashMap java/lang/Object java/lang/Object java/lang/Object),java/util/HashMap"
  prim__put : Java.Util.HashMap k v -> k -> v -> PrimIO v
  export %inline
  put : (HasIO io) => Java.Util.HashMap k v -> k -> v -> io (Maybe v)
  put arg0 arg1 arg2 = nullableToMaybe <$> primIO (prim__put arg0 arg1 arg2)
