module Main

-- `java.util.List` is generated by `--jvm-ffi-import java/util/List`. Its static factory
-- `List.of` has 12 overloads (of(), of(E), of(E,E), …, of(E...)). The generator gives every
-- overload the SAME name `of_` (`of` is an Idris keyword, hence the trailing `_`): the first
-- (of()) sits directly under `namespace List`, and each later overload sits in an arity-tagged
-- sub-namespace (`namespace Of2`, `namespace Of3`, …). So the caller never needs to know a
-- generated suffix — they write the unqualified `of_` and Idris picks the overload by arity/type.
import Java.Util

main : IO ()
main = do
  -- Unqualified `of_`: the 2-argument overload (of(E,E)) is selected purely by arity.
  -- (The type annotation is fully qualified because the marker `List` shadows `Prelude.List`.)
  xs <- the (IO (Java.Util.List String)) (of_ "x" "y")
  m  <- List.size xs
  printLn m                       -- expect 2

  -- The fully-qualified `List.Of3.of_` is the predictable escape hatch (arity in the tag),
  -- for when two overloads erase to the same Idris signature and the unqualified call is
  -- ambiguous. Here it just names the 3-argument overload (of(E,E,E)) explicitly.
  ys <- the (IO (Java.Util.List String)) (List.Of3.of_ "a" "b" "c")
  n  <- List.size ys
  printLn n                       -- expect 3
