-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java.Lang

public export
data Object : Type where [external]

public export
interface Inherits child parent where
  constructor MkInherits
  export %inline
  subtyping : child -> parent
  subtyping = believe_me

public export
Inherits a a where

public export
Inherits String Object where

export
%extern prim__javaLambda : (lambdaTy : Type) -> (intfTy : Type) -> (f : lambdaTy) -> intfTy

public export %inline
jlambda : {fTy : Type} -> (f : fTy) -> {intfTy : Type} -> intfTy
jlambda {fTy} f {intfTy} = prim__javaLambda fTy intfTy f

public export
%foreign "jvm:isNull(java/lang/Object boolean),java/util/Objects"
isNull : Object -> Bool

public export
nullableToMaybe : a -> Maybe a
nullableToMaybe value = if isNull (believe_me value) then Nothing else Just value
