-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Com.Example

import public Java.Lang

public export
data Greeter : Type where [external]

public export
Inherits Com.Example.Greeter Java.Lang.Object where

namespace Greeter
  %foreign "jvm:.greet(com/example/Greeter java/lang/String java/lang/String),com/example/Greeter"
  prim__greet : Com.Example.Greeter -> String -> PrimIO String
  export %inline
  greet : (HasIO io) => Com.Example.Greeter -> String -> io String
  greet arg0 arg1 = primIO (prim__greet arg0 arg1)

  %foreign "jvm:.nameLength(com/example/Greeter int),com/example/Greeter"
  prim__nameLength : Com.Example.Greeter -> PrimIO Int
  export %inline
  nameLength : (HasIO io) => Com.Example.Greeter -> io Int
  nameLength arg0 = primIO (prim__nameLength arg0)

  %foreign "jvm:of(java/lang/String com/example/Greeter),com/example/Greeter"
  prim__of_ : String -> PrimIO Com.Example.Greeter
  export %inline
  of_ : (HasIO io) => String -> io Com.Example.Greeter
  of_ arg0 = primIO (prim__of_ arg0)
