#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --nocolour tailrec.idr -o tailrec
java -Xss10m  \
  -cp \
  idris-jvm-runtime.jar:tailrec-classes \
  main.Main
rm -f tailrec tailrec.ibc
