#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ reg027.idr -o reg027
./reg027
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ reg027a.idr --check
rm -f reg027 *.ibc
