-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java.Util.Function

import Java.Lang
import System.FFI

public export %inline
Consumer : Type -> Type
Consumer ty0 = (Struct "java/util/function/Consumer accept" [], Java.Lang.Object -> ())

public export %inline
Predicate : Type -> Type
Predicate ty0 = (Struct "java/util/function/Predicate test" [], Java.Lang.Object -> Bool)

public export %inline
UnaryOperator : Type -> Type
UnaryOperator ty0 = (Struct "java/util/function/UnaryOperator apply" [], Java.Lang.Object -> Java.Lang.Object)
