-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java.Util.Function

import public Java.Lang
import public System.FFI

public export %inline
Consumer : Type -> Type
Consumer ty0 = (Struct "java/util/function/Consumer accept" [], Java.Lang.Object -> ())

public export %inline
Predicate : Type -> Type
Predicate ty0 = (Struct "java/util/function/Predicate test" [], Java.Lang.Object -> Bool)

public export %inline
UnaryOperator : Type -> Type
UnaryOperator ty0 = (Struct "java/util/function/UnaryOperator apply" [], Java.Lang.Object -> Java.Lang.Object)

public export %inline
Function : Type -> Type -> Type
Function ty0 ty1 = (Struct "java/util/function/Function apply" [], Java.Lang.Object -> Java.Lang.Object)

public export %inline
BiFunction : Type -> Type -> Type -> Type
BiFunction ty0 ty1 ty2 = (Struct "java/util/function/BiFunction apply" [], Java.Lang.Object -> Java.Lang.Object -> Java.Lang.Object)

public export %inline
BiConsumer : Type -> Type -> Type
BiConsumer ty0 ty1 = (Struct "java/util/function/BiConsumer accept" [], Java.Lang.Object -> Java.Lang.Object -> ())
