#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test001.idr -o test001 --partial-eval
./test001
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test001.idr --partial-eval --quiet --port none < input
rm -f test001 test001.ibc
