#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --nocolour issue83.idr -o issue83
java -Xss10m  \
  -cp \
  idris-jvm-runtime.jar:issue83-classes \
  main.Main
rm -f issue83 issue83.ibc
