#!/usr/bin/env bash

cp src/interactive015.idr .
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi "$@" --quiet --port none interactive015.idr < input

cat interactive015.idr

rm -f *.ibc interactive015.idr
