#!/usr/bin/env bash

${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test020.idr -o test020
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test020a.idr --check --nocolor
./test020
rm -f test020 *.ibc
