#!/usr/bin/env bash

cp src/interactive016.idr .
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi "$@" --quiet --port none interactive016.idr < input

cat interactive016.idr

rm -f *.ibc interactive016.idr
