#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ totality012.idr --check
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ totality012a.idr --check
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ totality012b.idr --check
rm -f *.ibc
