#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test003a.lidr --check
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test003.lidr -o test003
./test003
rm -f test003 test003.ibc Lit.ibc
