-- @generated by `idris2 --jvm-ffi-import` from JVM classpath reflection.
-- Do not edit by hand; regenerate instead.

module Java

namespace Lang
  public export
  data Object : Type where [external]

  public export
  data StringBuilder : Type where [external]

  public export
  data CharSequence : Type where [external]

  public export
  data StringBuffer : Type where [external]

  public export
  data AbstractStringBuilder : Type where [external]

  public export
  data Appendable : Type where [external]

  public export
  data Comparable : Type -> Type where [external]

namespace Io
  public export
  data Serializable : Type where [external]

namespace Lang
  public export
  interface Inherits child parent where
    constructor MkInherits
    export %inline
    subtyping : child -> parent
    subtyping = believe_me

  public export
  Inherits a a where

  public export
  Inherits String Object where

  export
  %extern prim__javaLambda : (lambdaTy : Type) -> (intfTy : Type) -> (f : lambdaTy) -> intfTy

  public export %inline
  jlambda : {fTy : Type} -> (f : fTy) -> {intfTy : Type} -> intfTy
  jlambda {fTy} f {intfTy} = prim__javaLambda fTy intfTy f

  public export
  %foreign "jvm:isNull(java/lang/Object boolean),java/util/Objects"
  isNull : Object -> Bool

  public export
  nullableToMaybe : a -> Maybe a
  nullableToMaybe value = if isNull (believe_me value) then Nothing else Just value

namespace Lang
  public export
  Inherits Java.Lang.StringBuilder Java.Lang.AbstractStringBuilder where

  public export
  Inherits Java.Lang.StringBuilder Java.Lang.Appendable where

  public export
  Inherits Java.Lang.StringBuilder Java.Io.Serializable where

  public export
  Inherits Java.Lang.StringBuilder (Java.Lang.Comparable x0) where

  public export
  Inherits Java.Lang.StringBuilder Java.Lang.CharSequence where

  public export
  Inherits Java.Lang.StringBuilder Java.Lang.Object where

namespace Lang
  namespace StringBuilder
    %foreign "jvm:<init>(java/lang/StringBuilder),java/lang/StringBuilder"
    prim__new : PrimIO Java.Lang.StringBuilder
    export %inline
    new : (HasIO io) => io Java.Lang.StringBuilder
    new = primIO prim__new

    %foreign "jvm:.append(java/lang/StringBuilder java/lang/Object java/lang/StringBuilder),java/lang/StringBuilder"
    prim__append : Java.Lang.StringBuilder -> Java.Lang.Object -> PrimIO Java.Lang.StringBuilder
    export %inline
    append : (HasIO io, Inherits a1 Java.Lang.Object) => Java.Lang.StringBuilder -> a1 -> io Java.Lang.StringBuilder
    append arg0 arg1 = primIO (prim__append arg0 (the Java.Lang.Object (subtyping arg1)))

    %foreign "jvm:.reverse(java/lang/StringBuilder java/lang/StringBuilder),java/lang/StringBuilder"
    prim__reverse : Java.Lang.StringBuilder -> PrimIO Java.Lang.StringBuilder
    export %inline
    reverse : (HasIO io) => Java.Lang.StringBuilder -> io Java.Lang.StringBuilder
    reverse arg0 = primIO (prim__reverse arg0)

    %foreign "jvm:.toString(java/lang/StringBuilder java/lang/String),java/lang/StringBuilder"
    prim__toString : Java.Lang.StringBuilder -> PrimIO String
    export %inline
    toString : (HasIO io) => Java.Lang.StringBuilder -> io String
    toString arg0 = primIO (prim__toString arg0)

    namespace Append1
      %foreign "jvm:.append(java/lang/StringBuilder java/lang/String java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1 : Java.Lang.StringBuilder -> String -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> String -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1 arg0 arg1)

    namespace Append1_2
      %foreign "jvm:.append(java/lang/StringBuilder java/lang/StringBuffer java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_2 : Java.Lang.StringBuilder -> Java.Lang.StringBuffer -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io, Inherits a1 Java.Lang.StringBuffer) => Java.Lang.StringBuilder -> a1 -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_2 arg0 (the Java.Lang.StringBuffer (subtyping arg1)))

    namespace Append1_3
      %foreign "jvm:.append(java/lang/StringBuilder java/lang/CharSequence java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_3 : Java.Lang.StringBuilder -> Java.Lang.CharSequence -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io, Inherits a1 Java.Lang.CharSequence) => Java.Lang.StringBuilder -> a1 -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_3 arg0 (the Java.Lang.CharSequence (subtyping arg1)))

    namespace Append3
      %foreign "jvm:.append(java/lang/StringBuilder java/lang/CharSequence int int java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append3 : Java.Lang.StringBuilder -> Java.Lang.CharSequence -> Int -> Int -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io, Inherits a1 Java.Lang.CharSequence) => Java.Lang.StringBuilder -> a1 -> Int -> Int -> io Java.Lang.StringBuilder
      append arg0 arg1 arg2 arg3 = primIO (prim__Append3 arg0 (the Java.Lang.CharSequence (subtyping arg1)) arg2 arg3)

    namespace Append1_4
      %foreign "jvm:.append(java/lang/StringBuilder [char java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_4 : Java.Lang.StringBuilder -> Object -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Object -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_4 arg0 arg1)

    namespace Append3_2
      %foreign "jvm:.append(java/lang/StringBuilder [char int int java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append3_2 : Java.Lang.StringBuilder -> Object -> Int -> Int -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Object -> Int -> Int -> io Java.Lang.StringBuilder
      append arg0 arg1 arg2 arg3 = primIO (prim__Append3_2 arg0 arg1 arg2 arg3)

    namespace Append1_5
      %foreign "jvm:.append(java/lang/StringBuilder boolean java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_5 : Java.Lang.StringBuilder -> Bool -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Bool -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_5 arg0 arg1)

    namespace Append1_6
      %foreign "jvm:.append(java/lang/StringBuilder char java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_6 : Java.Lang.StringBuilder -> Char -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Char -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_6 arg0 arg1)

    namespace Append1_7
      %foreign "jvm:.append(java/lang/StringBuilder int java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_7 : Java.Lang.StringBuilder -> Int -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Int -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_7 arg0 arg1)

    namespace Append1_8
      %foreign "jvm:.append(java/lang/StringBuilder long java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_8 : Java.Lang.StringBuilder -> Bits64 -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Bits64 -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_8 arg0 arg1)

    namespace Append1_9
      %foreign "jvm:.append(java/lang/StringBuilder float java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_9 : Java.Lang.StringBuilder -> Double -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Double -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_9 arg0 arg1)

    namespace Append1_10
      %foreign "jvm:.append(java/lang/StringBuilder double java/lang/StringBuilder),java/lang/StringBuilder"
      prim__Append1_10 : Java.Lang.StringBuilder -> Double -> PrimIO Java.Lang.StringBuilder
      export %inline
      append : (HasIO io) => Java.Lang.StringBuilder -> Double -> io Java.Lang.StringBuilder
      append arg0 arg1 = primIO (prim__Append1_10 arg0 arg1)
