#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ test005.idr -o test005
./test005
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ substring.idr -o substring
./substring < input
rm -f test005 substring *.ibc
