#!/usr/bin/env bash
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --check --nocolour error008.idr
${IDRIS:-idris} --portable-codegen jvm -p idrisjvmffi $@ --check --nocolour error008a.idr
rm -f *.ibc
